---
deployment:
  tasks:
    #- export DEPLOYPATH=/home/u5609877/futbolhonduras24.com/web/gh/
    - export DEPLOYPATH=/home/u5855787/iraffletv.online
    - /bin/cp -R * $DEPLOYPATH
    #- /usr/bin/rsync -av --exclude='.git' . $DEPLOYPATH
